### ISSUE TITLE
firmware-ethernet ExampleProject not working with udp_client_new.py 

### ISSUE THREAD

**Issue by nathankp** [RPeschke/SCROD_ETHERNET_V3#2]
I programmed the SCROD set up in the back room with with the ExampleProject. Then I ran the udp_client_new.py. I set proto_message =[0x00050004, WORD_PING_C, Word_command_ID, wordScrodRevC, WORD_COMMAND_C,0x00000005] to ping the SCROD. I also sent WORD_WRITE_C instead of PING to try and write to a register. The first number indicates the register value and number I tried to write. The script gets stuck waiting for a response. The script works fine on the ExampleProject located on the backroom PC: documents/firmware/t/.../scrodethernetexample

**Comment by RPeschke** [comment]
this looks like the data package is not formed correctly. The two version of Firmware do something completely different. the scrodethernetexample in this repository is actually trying to set registers etc. and therefore needs a exact data package the other on documents/firmware/t/.../scrodethernetexample is just sending back data as they come in it is similar to 

https://github.com/RPeschke/SCROD_ETHERNET_Example_SendBack/tree/c00834fa687d7ff6f99ec23f250b7cf1abe00890


@PsiStarPsi  has a very good documententation about how his project

https://github.com/PsiStarPsi/firmware-general/tree/c1389a2261958cff098db2948ee4860847159fd1

works. I am currently in Tokyo and don't have it with me but if you follow this instructions you will be able to run the >>scrodethernetexample <<. 

I am back at KEK on Monday and can look for the documentation.

**Comment by nathankp** [comment]
OK, so will search for instructions here: 
https://github.com/PsiStarPsi/firmware-general/tree/c1389a2261958cff098db2948ee4860847159fd1

and follow them while working with your firmware-ethernet fork, correct?

**Comment by RPeschke** [comment]
@nathankp  this is the document:

https://www.phys.hawaii.edu/~kurtisn/doku.php?id=itop:documentation:data_format


yes work with my fork for the moment

**Comment by nathankp** [comment]
Ok great thanks.
