### ISSUE TITLE
make_implementation.sh syntacx error

### ISSUE THREAD

**Issue by nathankp** [RPeschke/SCROD_ETHERNET_V3#3]
I am following your instructions from the Re:SCROD Ethernet email: 
 
"Next you type:
./make_implementation.sh scrodEthernetExample_Example_SendBack ./SCROD_ETHERNET_Example_SendBack/projectSrc/scrodEthernetExample.ucf"
There's a mysterious syntax error that is preventing me from building:
File "./make_implementation.sh", line 2
     echo "make ISE build system for $1"
                                                              ^
   SyntaxError: invalid syntax

**Comment by RPeschke** [comment]
can you check if the line endings are correct it should be \n (LF , ascii  character 13)

**Comment by nathankp** [comment]
So the line 2 needs to have \n?

**Comment by RPeschke** [comment]
the line ending of all files needs to be \n. the default for windows is \n\r the default for linux is \n and the default for mac is \r. most programs do not care about that except for bash scripts. that means if you have a bash script and it uses the wrong line endings it will break

**Comment by nathankp** [comment]
I made sure all lines have \n. I get the same error...

`#/bin/bash

echo "make ISE build system for $1"\n

python3 vhdl_build_system//vhdl_make_implementation.py $1 $2 \n

cp "protoBuild//simpleTemplate.xise.in"   "./build/$1/" \n

mv "./build/$1/simpleTemplate.xise.in"  "./build/$1/$1_simpleTemplate.xise.in" \n

python3 makeise//makeise.py "build/$1/$1.in" "build/$1/$1.xise" \n`

**Comment by RPeschke** [comment]
can you attache the file to the issue.

**Comment by nathankp** [comment]
It works now after following the README instructions.
It must be that I used the wrong paths: 
your email asked me to type: ./make_implementation.sh scrodEthernetExample_Example_SendBack ./SCROD_ETHERNET_Example_SendBack/projectSrc/scrodEthernetExample.ucf

but the readme said to type: ./make_implementation.sh scrodEthernetExample ./firmware-ethernet/ExampleProject/projectSrc/scrodEthernetExample.ucf

**Comment by RPeschke** [comment]
mh it should work either way. the first argument is the top level entity you want to build and the second one is the ucf file. 

Both of these files/entities should exist and work. maybe there are some more spelling errors somewhere. sry for that.

**Comment by nathankp** [comment]
That is OK. If I understand your comments in issue #2,  I think I don't want to build the _SendBack example project, because that doesn't do the full register operation. The project I just built is able to read and write registers correct?

**Comment by RPeschke** [comment]
the  _SendBack is a little easier to get started since it does not require you to get the UDP message correct. 

 But you are correct only the other one has a register.

**Comment by RPeschke** [comment]
can we close the issue or is there still something to discuss on this topic?

**Comment by nathankp** [comment]
I think we can close it.
